### PR TITLE
Ext integration

### PR DESCRIPTION
**Pull request by sandeep-paliwal**
Add impl to get extension point list from console lib 
Change impl of add/delete extension and init command to use the dynamic list instead of hardcoded one 
Add extension list command to list implemented extensions 
Add extension point list command to list extension points available for org 
TODO - add unit tests

## How Has This Been Tested?

manual tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by shazron** [comment]
I'm concerned about all those merge commits from adobe/master -- shouldn't this PR just contain the change commits?
Your branch should be branched off Moritz's branch cleanly.

```
# if you haven't clone the repo
git clone https://github.com/adobe/aio-cli-plugin-app
cd aio-cli-plugin-app
# add moritz's remote
git remote add moritzraho https://github.com/moritzraho/aio-cli-plugin-cna.git
# branch off his branch `ext-reg-integration` into new branch `my-fix`
git checkout -b my-fix  moritzraho/ext-reg-integration
```

I did this successfully for my PR https://github.com/moritzraho/aio-cli-plugin-cna/pull/2

**Comment by sandeep-paliwal** [comment]
@shazron let me create another clean branch off Moritz's branch and create PR using it.

**Comment by shazron** [comment]
@sandeep-paliwal this PR can be closed right

**Comment by sandeep-paliwal** [comment]
Yup, closing this one.

**Pull request closed without merging**
